version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    ECR_URI: 031988646265.dkr.ecr.us-east-1.amazonaws.com
    REPOSITORY_URI: 031988646265.dkr.ecr.us-east-1.amazonaws.com/todo-app
    ENVIRONMENT: prod

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION \
          | docker login --username AWS --password-stdin $ECR_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-8)
      - IMAGE_TAG=$COMMIT_HASH
      - FULL_TAG=$REPOSITORY_URI:$IMAGE_TAG
      - PROD_TAG=$REPOSITORY_URI:prod-$IMAGE_TAG
      - LATEST_TAG=$REPOSITORY_URI:latest

  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image $FULL_TAG...
      - docker build -f deploy/production/docker/Dockerfile -t $FULL_TAG .
      - docker tag $FULL_TAG $PROD_TAG
      - docker tag $FULL_TAG $LATEST_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing images to ECR...
      - docker push $FULL_TAG
      - docker push $PROD_TAG
      - docker push $LATEST_TAG
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"api","imageUri":"%s"}]' $FULL_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
