version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: todo_mysql_dev
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api:
    build:
      context: .
      dockerfile: deploy/develop/docker/Dockerfile
    container_name: todo_django_dev
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=todo_db
      - DB_USER=todo_user
      - DB_PASSWORD=todo_password
      - DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  mysql_data_dev: