[project]
name = "aws-code-pipe-line-demo-todo"
version = "0.1.0"
description = "a aws codepipeline demo using django"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django==4.2.0",
    "mysqlclient==2.2.0",
    "python-dotenv==1.0.0",
]
